### ISSUE TITLE
Protonvpn has some breaking changes

### ISSUE THREAD

**Issue by clemone210** [ivan-pinatti/docker-torrent-box-with-vpn#10]
## Describe the scenario
With the >7 releases of protonvpn there are some breaking changes.
Do you think you can integrate it?

**Comment by ivan-pinatti** [comment]
Hey @clemone210 ,

I can check it next weekend. 

It should be simple, just update the Docker image and check what parameters have changed.

**Comment by ivan-pinatti** [comment]
Hi @clemone210,

I've added the changes and validated that the new ProtonVPN Wireguard is working. There are a few changes that need to be made in the config files, please give it a read to the README instructions. Please test it and let me know if that worked for you.

In addition, please consider becoming a sponsor or buying me a coffee 😃 

[![](https://img.shields.io/static/v1?label=Sponsor&message=%E2%9D%A4&logo=GitHub&color=%23fe8e86)](https://github.com/sponsors/ivan-pinatti) 

<a href="https://www.buymeacoffee.com/ivan.pinatti" target="_blank"><img src="https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png" alt="Buy Me A Coffee" style="height: 41px !important;width: 174px !important;box-shadow: 0px 3px 2px 0px rgba(190, 190, 190, 0.5) !important;-webkit-box-shadow: 0px 3px 2px 0px rgba(190, 190, 190, 0.5) !important;" ></a>
