### ISSUE TITLE
Support Prowlarr

### ISSUE THREAD

**Issue by donnielrt** [ivan-pinatti/docker-torrent-box-with-vpn#14]
## Describe the Feature
Support the use of Prowlarr as a meta-indexer instead of/in addition to Jackett.

## Expected Behavior
The docker stack would include a pre-configured Prowlarr configuration which can be used in place of, or with Jackett.

## Use Case
Prowlarr works better with the *arr indexers and requires less configuration than Jackett. 

## Describe Ideal Solution
It would be great if one/both of Prowlarr and Jackett could be run, with the unused one uninstalled and any config settings removed/commented out.

## Alternatives Considered
Installing Prowlarr manually and removing Jackett and any configuration files.

## Additional Context
Haven't really used this docker configuration yet, so I might be missing something :)

**Comment by ivan-pinatti** [comment]
Hey @donnielrt,

I am working on a new release where it will be able to enable/disable apps, I will try to include this in the stack.

I am not sure that I can let both configured at the same time, it will have to be one or another. Would you care to elaborate a bit more why Prowlarr would be better solution overall?

Thanks and have a great week ahead.

**Comment by donnielrt** [comment]
Hi Ivan, cool, I'll try out the new release when it's out.

The main advantages of Prowlarr over Jackett is that it has automatically integrates with the *arr servers (Radarr, Sonarr, Readarr) out of the box. It also has a similar UI to those, and is pretty straightforward to set up compared to Jackett.

**Comment by ivan-pinatti** [comment]
Hey @donnielrt , the new release is published. 🚀 🚀 

Please read the documentation thoroughly as there are a lot of important details and give it a go.

Kind regards

**Comment by donnielrt** [comment]
Thanks Ivan! I'll give it a spin.
