### ISSUE TITLE
Routing Disabled

### ISSUE THREAD

**Issue by jusplainmike** [ivan-pinatti/docker-torrent-box-with-vpn#18]
I am getting this error in my nordvpn docker log. 

`[custom-init] No custom files found, skipping...
services-up: info: copying legacy longrun nordvpn (no readiness notification)
[ls.io-init] done.
FATAL: iptables is not functional. Ensure your container config adds --cap-add=NET_ADMIN,NET_RAW
--- Due to errors, routing has been disabled ---`

I am not able to access any of the services using reverse proxy or direct port access. 
I have the options added. 

`HostConfig
CapAdd
0 NET_ADMIN
1 NET_RAW
`

**Comment by ivan-pinatti** [comment]
HI @jusplainmike, if the VPN container is not running you won't be able to access, it has to be running.

Can you try creating a free ProtonVPN account and use it just for testing so we can isolate the problem of the NordVPN? Once you get everything working with the reverse proxy, we can focus on fixing the NordVPN container.

**Comment by jusplainmike** [comment]
The issue was Nord. I was able to login once I tried logging in using a token on my host directly. I presume it was latency in their authentication service. It was my first time using token system.
