### ISSUE TITLE
WebUI stops working for Qbit, Sonarr...etc

### ISSUE THREAD

**Issue by 5aberd2** [ivan-pinatti/docker-torrent-box-with-vpn#20]
## Describe the Bug

After running docker compose all containers are up but after 20-30 mins, all web ui fail to load (Sonarr ,Radarr, Qbit) mainly these three stop responding as in they dont load.
using protonVPN and Configured Correctly, tried the logs but nothing there to show me what could be, it's like the containers connected to the protonVPN network service are crashing/timing out, it just happened 

## Expected Behavior

they shouldn't crash

## Steps to Reproduce

for me i just run the docker compose and it happens after some time 

## Screenshots

![image](https://github.com/ivan-pinatti/docker-torrent-box-with-vpn/assets/93603153/85e2a3f3-6901-4057-8932-0d2f1d45c9af)
Logs of proton VPN Container
![image](https://github.com/ivan-pinatti/docker-torrent-box-with-vpn/assets/93603153/0c68379b-825d-475d-98a7-6a593b928a15)
all containers are still running
![image](https://github.com/ivan-pinatti/docker-torrent-box-with-vpn/assets/93603153/43cbf325-446b-4302-84f8-e0fb172df81d)
this is what is showing
## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:

Linux Kubuntu 
Docker version 20.10.23, build 7155243

## Additional Context

the only way for the web ui to come back online is to docker compose down the containers and up them again while keeping ProtonVPN Running

**Comment by ivan-pinatti** [comment]
Hello @5aberd2,

Did you follow all the steps in the documentation?
Using a simple `docker-compose up` won't work, you have to generate the `.env` file and use the `--profile` as well.

Let me know if that helps.

**Comment by 5aberd2** [comment]
> Hello @5aberd2,
> 
> Did you follow all the steps in the documentation?
> Using a simple `docker-compose up` won't work, you have to generate the `.env` file and use the `--profile` as well.
> 
> Let me know if that helps.

Yes I did all of that, I enabled what I needed and went through all the Readme documentation, I even started a new job.

**Comment by ivan-pinatti** [comment]
Are you using the free version of ProtonVPN? Is the connection getting dropped and reconnecting during this time period?

**Comment by 5aberd2** [comment]
Yes I'm using the free version of proton VPN, and during the timeout the connection, not that I saw it was getting dropped at the same time, as I can't even track what's making it go down, I'm suspecting that the issue is with VPN container, but the logs doesn't show anything out of the usual, I'm gonna try checking the connection before and during the timeout/unresponsiveness

**Comment by ivan-pinatti** [comment]
The might be the culprit, if the VPN container is not stable the other containers connections' won't as well.

Try changing the server and/or purchasing a paid plan, that might help.
