### ISSUE TITLE
Problem with unpack

### ISSUE THREAD

**Issue by clemone210** [ivan-pinatti/docker-torrent-box-with-vpn#8]
## Describe the Bug
nzbget error with unpack.
Downloading the file works flawlessly. Files are in the directory.
The unpack does not work. It always fails.

## Expected Behavior
After download, unpack and move to downloaded folder.

## Steps to Reproduce
/ 

## Screenshots
/
## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Ubuntu Server 20.04. LTS

## Additional Context
/

**Comment by ivan-pinatti** [comment]
Hello @clemone210,

Can you get the logs so we can investigate further?

Did you change OR checked the folder permissions?

**Comment by clemone210** [comment]
Found out that its due to permission.
Changed it, worked well afterwards.
